# Generated by Django 4.2.15 on 2026-07-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_add_organization_and_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='transfers_enabled_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
