# Generated by Django 4.2.15 on 2026-07-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_simplify_event_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurring_schedule',
            field=models.CharField(blank=True, help_text="Si el evento se repite, describí la frecuencia (ej: 'Todos los sábados 21hs'). Dejá vacío si es un evento único.", max_length=200, verbose_name='Repetición'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(verbose_name='Fecha del evento'),
        ),
    ]
