# Generated by Django 4.2.15 on 2026-07-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_add_recurring_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Si está marcado, cada entrada representa una función con su propia fecha.', verbose_name='Evento recurrente'),
        ),
    ]
