# Generated by Django 4.2.15 on 2026-07-10 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_add_is_recurring_occurrence_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
    ]
