# Generated by Django 4.2.15 on 2026-07-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_remove_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, help_text='Physical address of the event', max_length=500),
        ),
    ]
