# Generated by Django 4.2.15 on 2026-07-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_event_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='header_image',
            field=models.ImageField(blank=True, help_text="Dimensions: 1666px x 500px. If left empty, the organization's photo will be used.", null=True, upload_to='events/heros'),
        ),
    ]
