# Generated by Django 4.2.15 on 2026-07-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_event_header_image_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invitations_count',
            field=models.PositiveIntegerField(default=0, help_text='Entradas reservadas como invitaciones. Se descuentan del cupo disponible para la venta.'),
        ),
    ]
