# Generated by Django 4.2.15 on 2026-07-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_invitations_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelado')], default='draft', help_text='Draft events are not publicly visible', max_length=20),
        ),
    ]
