# Generated by Django 4.2.15 on 2026-07-13 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_event_status_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reservations_closed',
            field=models.BooleanField(default=False, help_text='Cuando está activo, no se pueden comprar nuevas entradas para este evento.'),
        ),
        migrations.CreateModel(
            name='EventInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('checked_in', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='events.event')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
