# Generated by Django 4.2.15 on 2026-07-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_reservations_closed_and_invitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ciudad',
            field=models.CharField(blank=True, help_text='City where the event takes place', max_length=200),
        ),
    ]
