# Generated by Django 4.2.15 on 2026-07-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0050_add_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='apto_menores',
            field=models.BooleanField(default=False, help_text='Marcar si el evento es apto para menores de 18 años', verbose_name='Apto para menores de 18 años'),
        ),
    ]
