# Generated by Django 4.2.15 on 2026-07-10 01:28

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, help_text='Default physical address for events', max_length=500),
        ),
        migrations.AddField(
            model_name='organization',
            name='location',
            field=models.CharField(blank=True, help_text='Default venue name for events', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='location_url',
            field=models.URLField(blank=True, help_text='Default location URL (e.g. Google Maps) for events', max_length=500),
        ),
        migrations.AddField(
            model_name='organization',
            name='photo',
            field=models.ImageField(blank=True, help_text='Default header image for events', null=True, upload_to='organizations/photos'),
        ),
    ]
