# Generated by Django 4.2.15 on 2026-07-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Default city for events', max_length=200),
        ),
    ]
