# Generated by Django 4.2.15 on 2026-08-03 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_add_ciudad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='mp_access_token',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='mp_marketplace_fee_pct',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='mp_public_key',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='mp_refresh_token',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='mp_token_expires_at',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='mp_user_id',
        ),
    ]
