# Generated by Django 4.2.15 on 2026-08-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_remove_mercadopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='mp_access_token',
            field=models.CharField(blank=True, help_text='Seller access token (obtained via OAuth)', max_length=500),
        ),
        migrations.AddField(
            model_name='organization',
            name='mp_marketplace_fee_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Marketplace fee percentage (e.g. 5.00 = 5%). Leave at 0 to charge no fee.', max_digits=5),
        ),
        migrations.AddField(
            model_name='organization',
            name='mp_nickname',
            field=models.CharField(blank=True, help_text='Seller MP alias/nickname (e.g. JUAN.PEREZ)', max_length=200),
        ),
        migrations.AddField(
            model_name='organization',
            name='mp_public_key',
            field=models.CharField(blank=True, help_text='Seller public key', max_length=500),
        ),
        migrations.AddField(
            model_name='organization',
            name='mp_refresh_token',
            field=models.CharField(blank=True, help_text='Token to refresh the access token', max_length=500),
        ),
        migrations.AddField(
            model_name='organization',
            name='mp_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the access token expires', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='mp_user_id',
            field=models.CharField(blank=True, help_text='Seller MercadoPago user ID', max_length=100),
        ),
    ]
