# Generated by Django 4.2.15 on 2026-08-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_eventproduct_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cajasale',
            name='mp_order_id',
        ),
        migrations.RemoveField(
            model_name='cajasale',
            name='mp_payment_id',
        ),
        migrations.RemoveField(
            model_name='cajasale',
            name='mp_qr_data',
        ),
        migrations.RemoveField(
            model_name='cajasale',
            name='processor_callback',
        ),
        migrations.AlterField(
            model_name='cajasale',
            name='payment_method',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia')], max_length=20),
        ),
        migrations.DeleteModel(
            name='EventCajaMercadoPagoConfig',
        ),
    ]
