# Generated by Django 4.2.15 on 2024-03-21 20:00
# FIXED: is_used was already added by 0045_newticket_used; this migration is a no-op.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0052_merge_20250423_1914'),
    ]

    operations = [
        # Column already exists from 0045_newticket_used; nothing to do.
    ]
