# Generated by Django 4.2.15 on 2026-07-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0071_alter_order_order_type_alter_tickettype_ticket_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='occurrence_date',
            field=models.DateTimeField(blank=True, help_text='Para eventos recurrentes: fecha y hora de esta función específica.', null=True, verbose_name='Fecha de la función'),
        ),
    ]
