# Generated by Django 4.2.15 on 2026-07-09 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0072_add_is_recurring_occurrence_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='donation_art',
        ),
        migrations.RemoveField(
            model_name='order',
            name='donation_grant',
        ),
        migrations.RemoveField(
            model_name='order',
            name='donation_venue',
        ),
    ]
