# Generated by Django 4.2.15 on 2026-07-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0073_remove_donation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='occurrence_end',
            field=models.DateTimeField(blank=True, help_text='Para eventos recurrentes: hora de finalización de esta función (opcional).', null=True, verbose_name='Fin de la función'),
        ),
    ]
