# Generated by Django 4.2.15 on 2026-07-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0074_occurrence_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mp_preference_id',
            field=models.CharField(blank=True, default='', help_text='Cached MercadoPago preference ID', max_length=200),
        ),
    ]
