# Generated by Django 4.2.15 on 2026-08-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0075_add_mp_preference_id_to_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mp_preference_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('INTERNATIONAL_TRANSFER', 'Transferencia Internacional'), ('LOCAL_TRANSFER', 'Transferencia Local'), ('ONLINE_PURCHASE', 'Compra Online'), ('CASH_ONSITE', 'Efectivo'), ('OTHER', 'Otro')], default='ONLINE_PURCHASE', max_length=32),
        ),
    ]
